<h3>REPLACING MISSING TEETH</h3>

<div id="subpages">
	<div id="<? print $selected_subpage[1] ?>">
		<h2>Dental Implants to Replace Missing Teeth</h2>
		<p>You may be missing one or more teeth as a result of periodontal disease or trauma. Perhaps that adult tooth may never have come in.  You know that your confidence about your teeth affects how you feel about yourself, both personally and professionally. Perhaps you hide your smile because of spaces from missing teeth. Maybe your dentures don't feel secure. Perhaps you have difficulty chewing. If you are missing one or more teeth and would like to smile, speak and eat again with comfort and confidence, there is good news! Dental implants are teeth that can look and feel just like your own! Under proper conditions, such as placement by Drs. Goteiner and Shah and diligent patient maintenance, implants can last a lifetime.
	</div>
	
	<div id="<? print $selected_subpage[2] ?>">
		<h2>What Dental Implants Can Do?</h2>
		<ul>
			<li>Replace one or more teeth without affecting bordering teeth.
			<li>Support a bridge and eliminate the need for a removable partial denture.
			<li>Provide support for a denture, making it more secure and comfortable.
		</ul>
	</div>
	
	<div id="<? print $selected_subpage[3] ?>">
		<h2>Replacing A Single Tooth</h2>
		<p>A dental implant provides several advantages over tooth replacement options.  In addition to looking and function like a natural tooth, a dental implant replaces a single tooth without sacrificing the health of neighboring teeth.  The other common treatment for the loss of a single tooth, a tooth supported fixed bridge, requires that adjacent teeth be ground down to support the cemented bridge.
		<p>Because a dental implant will replace your tooth root, the bone is better preserved.  With a bridge, some of the bone that previously surrounded the tooth begins to resorb (deteriorate).  Dental implants integrate with your jawbone, helping to keep the bone healthy and intact.
		<p>In the long term, A single implant can be more esthetic and easier to keep clean than a bridge.  Gums can recede around a bridge, leaving a visible defect when the metal base or collar of the bridge becomes exposed.  Resorbed bone beneath the bridge can lead to an unattractive smile.  Another concern is the cement holding the bridge in place can wash out allowing bacteria to decay the teeth that anchor the bridge.
	</div>
	
	<div id="<? print $selected_subpage[4] ?>">
		<h2>Replacing Several Teeth</h2>
		<p>Dental implants provide several advantages over other teeth replacement options.  In addition to looking and functioning like natural teeth, implant-supported bridges replace teeth without adjacent natural teeth.  Other common treatments for the loss of several teeth, such as fixed bridges or removable partial dentures, are dependent on support from adjacent teeth.
		<p>In addition, because implant-supported bridges will replace some of your tooth roots, your bone is better preserved.  With a fixed bridge or removable partial denture, the bone that surrounded the tooth root may begin to resorb (deteriorate).  Dental implants integrate with your jawbone, helping to keep the bone healthy and intact.
		<p>In the long term, implants are esthetic, functional and comfortable.  Gums and bone can recede around a fixed bridge or removable partial denture, leaving a visible defect.  Resorbed bone beneath bridges or removable partial denture can lead to a collapsed, unattractive smile.  Another concern is the cement holding the bridge in place can wash out allowing bacteria to decay the teeth that anchor the bridge.  In addition, removable partial dentures can move around in the mouth and reduce your ability to eat certain foods.
	</div>
	
	<div id="<? print $selected_subpage[5] ?>">
		<h2>Replacing All Of Your Teeth</h2>
		<p>Dental implants provide several advantages over other teeth replacement options.  In addition to looking and functioning like natural teeth, implant supported full bridges or dentures are designed to be long lasting.  Implant-supported full bridges also are more comfortable and stable than conventional dentures, allowing you to retain a more natural biting and chewing capacity.
		<p>In addition, because implant supported full bridged and dentures will replace some of your tooth roots your bone is better preserved.  With conventional dentures, the bone that previously surrounded the tooth roots begins to resorb (deteriorate).  Dental implants integrate with your jawbone, helping to keep the bone healthy and intact.
		<p>In the long term, implants can be more esthetic and easier to maintain than conventional dentures.  The loss of bone that accompanies conventional dentures leads to recession of the jawbone and a collapsed, unattractive smile.  Conventional dentures make it difficult to eat certain foods.
		<p>See us for consultation to see if you are a candidate for implant dentistry. Drs. Goteiner and Shah work closely in conjunction with your restorative dentist for the most aesthetic, functional result.
	</div>
	
	<div id="<? print $selected_subpage[6] ?>">
		<h2>Sinus Augmentation</h2>
		<p>On occasion you may require extra bone to place an implant in the molar area of your upper teeth.  Besides that traditional Caldwell-Luck procedure this office uses the much more conservative and less traumatic Summer’s osteotome technique.  With the Summer’s technique the implant can be placed 4 months after the procedure.
		<p align='center'><a href='images/II-1.jpg'><img src='images/II-1_small.jpg' width='400' border='0'></a>
		<p align='center'><a href='images/II-3.jpg'><img src='images/II-3_small.jpg' width='400' border='0'></a>
	</div>
	
	<div id="<? print $selected_subpage[7] ?>">
		<h2>Ridge Augmentation and Expansion</h2>
		<p>This technique is used to add bone to both the upper and lower jaw so that the implant can be properly place.  It also can assist in getting rid of that &quot;sunken look&quot; that often occurs after you have lost teeth.
		<p align='center'><a href='images/I-2.jpg'><img src='images/I-2_small.jpg' width='400' border='0'></a>
		<p align='center'><a href='images/lipsupport.jpg' alt='Ridge Augmentation to Improve the Esthetics of the New Crowns and Improve Support of the Lips'><img src='images/lipsupport_small.jpg' width='400' border='0' alt='Ridge Augmentation to Improve the Esthetics of the New Crowns and Improve Support of the Lips'></a>
	</div>
	
	<div id="<? print $selected_subpage[8] ?>">
		<h2>Immediate Load Implants</h2>
		<p>On occasion we can extract a broken tooth, place the implant and cap (crown) all in the same visit.  In this way the is no need to wear any type of removable appliance while waiting to get your final crown
		<p>See us for consultation to see if you are a candidate for an immediately loaded implant.   Drs. Goteiner and Shah work closely in conjunction with your restorative dentist for the most aesthetic, functional result.
	</div>
</div>

